packages:
  - 'apps/*'

catalogMode: prefer

catalogs:
  cms:
    '@sanity/code-input': ^7.1.0
    '@sanity/icons': ^3.7.4
    '@sanity/vision': ^5.20.0
    react: ^19.2.4
    react-dom: ^19.2.4
    sanity: ^5.20.0
    styled-components: ^6.1.18
  eslint:
    '@antfu/eslint-config': ^3.2.2
    eslint: ^9.39.4
    eslint-plugin-format: ^2.0.1
  site:
    '@iconify-json/carbon': ^1.2.20
    '@portabletext/to-html': ^5.0.2
    '@sanity/client': ^7.20.0
    '@sanity/image-url': ^2.1.1
    feed: ^5.2.1
    groq: ^5.20.0
    shiki: ^4.0.2
    unocss: ^66.6.8
    vitepress: ^2.0.0-alpha.17
    vue: ^3.5.32
  typescript:
    '@sanity/types': ^5.20.0
    '@types/node': ^25.6.0
    '@types/react': ^19.2.14
    typescript: ^5.9.0
  utils:
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    vite: ^7.3.1

cleanupUnusedCatalogs: true

shellEmulator: true
