name: ci
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: formatting
        run: deno fmt --check

      - name: lint
        run: deno lint

      - name: typecheck
        run: deno check main.ts
